//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 08:59:43 AM CET 
//


package dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rentalCompany complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rentalCompany">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="rentals" type="{}rental" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rentalCars" type="{}rentalCar" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="rentalBuses" type="{}rentalBus" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rentalCompany", propOrder = {
    "id",
    "rentals",
    "name",
    "rentalCars",
    "rentalBuses"
})
public class RentalCompany {

    protected int id;
    protected List<Rental> rentals;
    @XmlElement(required = true)
    protected String name;
    protected List<RentalCar> rentalCars;
    protected List<RentalBus> rentalBuses;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the rentals property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rentals property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRentals().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rental }
     * 
     * 
     */
    public List<Rental> getRentals() {
        if (rentals == null) {
            rentals = new ArrayList<Rental>();
        }
        return this.rentals;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the rentalCars property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rentalCars property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRentalCars().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RentalCar }
     * 
     * 
     */
    public List<RentalCar> getRentalCars() {
        if (rentalCars == null) {
            rentalCars = new ArrayList<RentalCar>();
        }
        return this.rentalCars;
    }

    /**
     * Gets the value of the rentalBuses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rentalBuses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRentalBuses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RentalBus }
     * 
     * 
     */
    public List<RentalBus> getRentalBuses() {
        if (rentalBuses == null) {
            rentalBuses = new ArrayList<RentalBus>();
        }
        return this.rentalBuses;
    }

}
